- name: Ensure build directory exists
  file:
    path: "{{ build_root }}"
    state: directory

- name: Download Erlang/OTP sources
  unarchive:
    url: "http://erlang.org/download/{{ otp_basename }}.tar.gz"
    dest: "{{ otp_build_dir }}"


- name: Configure Erlang build
  shell: >-
    ./configure --prefix="/usr"
  args:
    creates: Makefile
    chdir: "{{ otp_build_dir }}"

- name: Build Erlang
  shell: >-
    make -j 8 && touch made
  args:
    chdir: "{{ otp_build_dir }}"
    creates: "{{ otp_build_dir }}/made"

- name: Run make install
  shell: >-
    make install && touch installed
  args:
    chdir: "{{ otp_build_dir }}"
    creates: "{{ otp_build_dir }}/installed"
  become: yes

- name: Download Elixir sources
  git:
    repo: https://github.com/elixir-lang/elixir.git
    dest: "{{ ex_build_dir }}/"
    update: no

- name: Run make for Elixir
  shell: >-
    make -j 6 && touch made
  args:
    chdir: "{{ ex_build_dir }}"
    creates: "{{ ex_build_dir }}/made"

- name: Run make install
  shell: >-
    make install && touch installed
  args:
    chdir: "{{ ex_build_dir }}"
    creates: "{{ ex_build_dir }}/installed"
  become: yes
