- name: Stop Elixir
  shell:
    "{{ MENV }} rel/planties/bin/planties stop || true"
  args:
    chdir: "{{ project_path }}"

- name: Start Elixir
  shell:
    "{{ MENV }} rel/planties/bin/planties start"
  args:
    chdir: "{{ project_path }}"
  when: ansible_nodename != "f21"
