- name: Uploading code
  synchronize:
    src: "../../{{ project }}/"
    dest: "{{ project_path }}/"
    # delete: yes
    rsync_opts:
      - --exclude=deps
      - --exclude=_build
      - --exclude=rel
      - --exclude=.git
      - --exclude=run.sh
      - --exclude=error.log
      - --exclude=rel/planties/
  when: ansible_nodename == "raspberrypi"

- name: Update timestamps on files (force recompilation)
  shell: >-
    touch {{ project_path }}/lib/*
