- name: "Uploading code"
  synchronize:
    src: "../../planties/"
    dest: "{{ home_path }}/planties/"
    delete: yes
    rsync_opts:
      - "--exclude=deps"
      - "--exclude=_build"
      - "--exclude=rel"
      - "--exclude=.git"
      - "--exclude=run.sh"
      - "--exclude=rel/planties/"
  when: ansible_nodename == "raspberrypi"
