- include_vars: "config/vars.yml"
  tags:
    - restart
    - build
- include_vars: "config/{{ ansible_nodename }}.yml"
  tags:
    - restart
    - build

- name: "Uploading code"
  synchronize:
    src: "../../planties/"
    dest: "{{ home_path }}/planties/"
    rsync_opts:
      - "--exclude=deps"
      - "--exclude=_build"
      - "--exclude=rel"
      - "--exclude=.git"
      - "--exclude=run.sh"
      - "--exclude=rel/planties/"

- name: "Generate vm.args"
  template:
    src: "config/vm.args"
    dest: "{{ project_path }}/rel/vm.args"


- name: "Get mix deps"
  shell: mix deps.get
  args:
    chdir: "{{ project_path }}"

- name: "Mix compile"
  shell: mix compile
  args:
    chdir: "{{ project_path }}"

- name: "Remove previous release"
  tags: build
  file:
    path: "{{ project_path }}/rel/planties"
    state: "absent"

- name: "Build Elixir release"
  shell:
    MIX_ENV={{ mix_env }} mix release
  tags: build
  args:
    chdir: "{{ project_path }}"

- name: "Stop Elixir"
  tags: restart
  shell:
    rel/planties/bin/planties stop || true
  args:
    chdir: "{{ project_path }}"

- name: "Start Elixir"
  tags: restart
  shell:
    rel/planties/bin/planties start
  args:
    chdir: "{{ project_path }}"
  when: ansible_nodename != "f21"
