- include_vars: "config/vars.yml"
- include_vars: "config/{{ ansible_nodename }}.yml"

- name: "Uploading code"
  synchronize:
    src: "../../planties/"
    dest: "{{ home_path }}/planties/"
    rsync_opts:
      - "--exclude=deps"
      - "--exclude=_build"
      - "--exclude=rel"
      - "--exclude=.git"
      - "--exclude=run.sh"
      - "--exclude=rel/planties/"

- name: "Generate vm.args"
  template:
    src: "config/vm.args"
    dest: "{{ project_path }}/rel/vm.args"

- file:
    path: "{{ project_path }}/rel/planties"
    state: "absent"

- name: "Get mix deps"
  shell: mix deps.get
  args:
    chdir: "{{ project_path }}"


- name: "Mix compile"
  shell: mix compile
  args:
    chdir: "{{ project_path }}"

- name: "Build Elixir release"
  shell:
    MIX_ENV={{ mix_env }} mix release
  args:
    chdir: "{{ project_path }}"
