- include_vars: "config/vars.yml"
  tags:
    - restart
    - build
- include_vars: "config/{{ ansible_nodename }}.yml"
  tags:
    - restart
    - build

- include: "tasks/sync.yml"

- name: "Generate vm.args"
  template:
    src: "config/vm.args"
    dest: "{{ project_path }}/rel/vm.args"


- name: "Get mix deps"
  shell: mix deps.get
  args:
    chdir: "{{ project_path }}"

- name: "Mix compile"
  shell: "{{ MENV }} mix compile"
  args:
    chdir: "{{ project_path }}"

- name: "Remove previous release"
  tags: build
  file:
    path: "{{ project_path }}/rel/planties"
    state: "absent"

- name: "Build Elixir release"
  shell:
     "{{ MENV }} mix release --dev"
  tags: build
  args:
    chdir: "{{ project_path }}"

- include: "tasks/restart_release.yml"
