- include: tasks/sync.yml

- name: Make rel directory if needed
  file:
    state: directory
    path: "{{ project_path }}/rel/"

- name: Generate vm.args
  template:
    src: config/vm.args
    dest: "{{ project_path }}/rel/vm.args"

- name: Get mix deps
  shell: "{{ MENV }} mix deps.get"
  args:
    chdir: "{{ project_path }}"

- name: Run mix compile
  shell: "{{ MENV }} mix compile"
  args:
    chdir: "{{ project_path }}"

- name: Remove previous release
  file:
    path: "{{ project_path }}/rel/planties"
    state: absent

- name: Build Elixir release
  shell: >-
    {{ MENV }} mix release --dev
  args:
    chdir: "{{ project_path }}"


- include: tasks/restart_release.yml
