- include_vars: "config/vars.yml"
- include_vars: "config/{{ ansible_nodename }}.yml"

- name: "Uploading code"
  synchronize:
    src: "../../planties/"
    dest: "{{ home_path }}/planties/"
    rsync_opts:
      - "--exclude=deps"
      - "--exclude=_build"
      - "--exclude=rel"
      - "--exclude=.git"
      - "--exclude=run.sh"

- name: "Generate run.sh script"
  template:
    src: "config/run.sh"
    dest: "{{ project_path }}/run.sh"
    mode: "0777"

- name: "Generate console.sh script"
  template:
    src: "config/console.sh"
    dest: "{{ project_path }}/console.sh"
    mode: "0777"

- name: "Get mix deps"
  shell: mix deps.get
  args:
    chdir: "{{ project_path }}"

- name: "Mix compile"
  shell: mix compile
  args:
    chdir: "{{ project_path }}"
