- include_vars: "config/vars.yml"
- include_vars: "config/{{ ansible_nodename }}.yml"

- include: "tasks/sync.yml"

- name: Compile release
  shell:
    mix compile
  args:
    chdir: "{{ project_path }}"

- include: "tasks/restart_release.yml"
